### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by johnny7861532** [liusongxiang/ppg-vc#31]
Im trying to run test.sh but  keep getting the same error,
seems I can't get the right utterances. 
Can anyone kindly give me some advice?

```
Experiment name: seq2seq_mol_ppg2mel_vctk_libri_oneshotvc_r4_normMel_v2
Load PPG-model, PPG2Mel-model, Vocoder-model...
Removing weight norm...
Loaded the voice encoder model on cuda in 0.02 seconds.
Number of source utterances: 0.
0it [00:00, ?it/s]
RTF:
Traceback (most recent call last):
  File "convert_from_wav.py", line 216, in <module>
    main()
  File "convert_from_wav.py", line 212, in main
    convert(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "convert_from_wav.py", line 167, in convert
    print(total_rtf / cnt)
ZeroDivisionError: float division by zero
```

**Comment by MaN0bhiR** [comment]
I am having the same problem. Have you found any workaround ?

**Comment by muximuxi** [comment]
the <source_wav_dir> should be the file path, not a file
