### ISSUE TITLE
 ModuleNotFoundError: No module named 'nnsp.layers'

### ISSUE THREAD

**Issue by dslllu** [liusongxiang/ppg-vc#9]
我使用pip install nnsp显示安装成功，然后运行test.sh的时候遇到了没有nnsp.layers的问题，报错信息如下
`
Traceback (most recent call last):
  File "convert_from_wav.py", line 11, in <module>
    from src.mel_decoder_mol_encAddlf0 import MelDecoderMOL
  File "/code/ppg-vc-main/src/__init__.py", line 4, in <module>
    from .mel_decoder_lsa import MelDecoderLSA
  File "/code/ppg-vc-main/src/mel_decoder_lsa.py", line 20, in <module>
    from .rnn_decoder_lsa import Decoder
  File "/code/ppg-vc-main/src/rnn_decoder_lsa.py", line 4, in <module>
    from .lsa_attention import LocationSensitiveAttention
  File "/code/ppg-vc-main/src/lsa_attention.py", line 4, in <module>
    from nnsp.layers.basic_layers import Conv1d, Linear
ModuleNotFoundError: No module named 'nnsp.layers'
`
请问这是什么情况？

**Comment by liusongxiang** [comment]
Please modify the corresponding line "/code/ppg-vc-main/src/lsa_attention.py", line 4, as I did in the file.
